server:
    port: 8002

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
    application:
      name: center-privilege-service

logging:
    level:
        root: INFO
        org.hibernate: INFO
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        org.bibernate.type.descriptor.sql.BasicExtractor: TRACE
        com.springms: DEBUG

eureka:
    client:
        service-url:
            defaultZone: http://admin:admin@localhost:8000/eureka
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
        appname: center-privilege-service
        hostname: localhost